name = "Mypackage"
uuid = "8d1d1260-d180-43af-b4e6-79bc30453e85"
authors = ["Debraj Bhal"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets="1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test","SafeTestsets"]
